# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'
Rails.application.config.assets.precompile += %w( jquery-1.11.1.js )
Rails.application.config.assets.precompile += %w( accordion/accordion-cignex-min.js )
Rails.application.config.assets.precompile += %w( intlTelInput.js )
Rails.application.config.assets.precompile += %w( utils.js )
Rails.application.config.assets.precompile += %w( jquery-video-lightning.js )
Rails.application.config.assets.precompile += %w( functions.js )
Rails.application.config.assets.precompile += %w( bootstrap.js )
Rails.application.config.assets.precompile += %w( jquery.knob.min.js )
Rails.application.config.assets.precompile += %w( bootstrap-datepicker.js )
Rails.application.config.assets.precompile += %w( bootstrap-datetimepicker.min.js )
Rails.application.config.assets.precompile += %w( overhaulbids.js )
Rails.application.config.assets.precompile += %w( parsley.js )
Rails.application.config.assets.precompile += %w( jquery.alphanum.js )
Rails.application.config.assets.precompile += %w( jquery.tmpl.js )
Rails.application.config.assets.precompile += %w( jquery.plugin.js )
Rails.application.config.assets.precompile += %w( jquery.datepick.js )
Rails.application.config.assets.precompile += %w( jquery.datepick.css )
Rails.application.config.assets.precompile += %w( jquery.datetimepicker.js )
Rails.application.config.assets.precompile += %w( account.js )
Rails.application.config.assets.precompile += %w( project.js )
Rails.application.config.assets.precompile += %w( jquery.form-validator.js )
Rails.application.config.assets.precompile += %w( css3-gmail-style.css )
Rails.application.config.assets.precompile += %w( messages_gmail.css )
Rails.application.config.assets.precompile += %w( jquery.selectbox.js )
Rails.application.config.assets.precompile += %w( select_box.css )
Rails.application.config.assets.precompile += %w( workroom.js )
Rails.application.config.assets.precompile += %w( jquery.multifile.js )
Rails.application.config.assets.precompile += %w( jquery.form.js )
Rails.application.config.assets.precompile += %w( jquery-ui.js )
Rails.application.config.assets.precompile += %w( jquery-ui-slider-pips.js )
Rails.application.config.assets.precompile += %w( bootbox.js )
Rails.application.config.assets.precompile += %w( feedback.js )
Rails.application.config.assets.precompile += %w( jquery.confirm.js )
Rails.application.config.assets.precompile += %w( jquery.youtubepopup.js )
Rails.application.config.assets.precompile += %w( mm.js )
Rails.application.config.assets.precompile += %w( flash.css )
Rails.application.config.assets.precompile += %w( alert.css )
Rails.application.config.assets.precompile += %w( moment.js )
Rails.application.config.assets.precompile += %w( jquery.simple-dtpicker.js )
Rails.application.config.assets.precompile += %w( jquery.simple-dtpicker.css )
Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( blue.css )
Rails.application.config.assets.precompile += %w( default.css )
Rails.application.config.assets.precompile += %w( green.css )
Rails.application.config.assets.precompile += %w( header_footer.css )
#Rails.application.config.assets.precompile += %w( demo.js )
Rails.application.config.assets.precompile += %w( testimonial.css )
Rails.application.config.assets.precompile += %w( advertisements.js )
Rails.application.config.assets.precompile += %w( jquery.countdown.js )

Rails.application.config.assets.precompile += %w( jquery.maxlength.min.js )
Rails.application.config.assets.precompile += %w( jquery.maxlength.css )
# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
 #Rails.application.config.assets.precompile += %w( search.js )
